version: '3.8'
services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
